# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy version catalog to Nexus and plugins to Gradle Portal."
  lane :deploy do
    gradle(task: "publishToSonatype closeAndReleaseSonatypeStagingRepository")
    gradle(task: "publishPlugins")
  end

  desc "Deploy libraries to Maven locally on the PC."
    lane :deployLocal do
      gradle(task: "publishToMavenLocal")
    end
end